In [ ]:
from dotenv import load_dotenv
import os
import time  # <--- agrega esta línea
import json
import requests

# Ruta .env en la raíz del repo
env_path = os.path.abspath(os.path.join(os.getcwd(), "../../..", ".env"))
load_dotenv(dotenv_path=env_path)

# Obtener clave de Grok desde .env
GROK_API_KEY = os.getenv("GROK_API_KEY")

if GROK_API_KEY:
    print("Clave de Grok cargada correctamente.")
else:
    raise ValueError("❌ No se encontró la clave de Grok. Verifica la ruta del .env.")

Clave de Grok cargada correctamente.

In [ ]:
def call_grok_api(prompt, text):
    """
    Envía un texto y un prompt al modelo Grok-4 y devuelve el resumen generado.
    """
    url = "https://api.x.ai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {GROK_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "grok-4",
        "messages": [
            {"role": "system", "content": "Eres un asistente experto en simplificar lenguaje biomédico."},
            {"role": "user", "content": f"{prompt}\n\nTexto:\n{text}"}
        ]
    }

    try:
        start_time = time.time()
        response = requests.post(url, headers=headers, json=payload)
        elapsed = time.time() - start_time

        # Mostrar más información si algo falla
        print(f"Código de estado: {response.status_code}")
        try:
            print("Respuesta (primeros 200 caracteres):", response.text[:200])
        except Exception as e:
            print("No se pudo imprimir el texto:", e)

        if response.status_code == 200:
            data = response.json()
            # Muestra las claves del JSON
            print("Claves en respuesta:", data.keys())
            output = data["choices"][0]["message"]["content"]
            return output.strip(), elapsed
        else:
            print(f"Error HTTP {response.status_code}: {response.text}")
            return None, elapsed
    except Exception as e:
        print("Error en la solicitud:", e)
        return None, None

In [ ]:
import pandas as pd
#traemos el archivo test.csv
ruta_dataset = "../data-sources/pre-processed/data_finetuning_test.csv"
df = pd.read_csv(ruta_dataset, encoding="utf-8", on_bad_lines="skip")
display(df.head(2))

,name,article,summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...

In [ ]:
# Prompt a utilizarse
prompt = """You are a helpful medical/health writer.
Summarize the following scientific text into a clear summary intended for a general audience.
Do NOT use headings, titles, bullet points, or numbered lists. Do not invent data or references.
If you must use a technical term, briefly define it."""

# Tomar las dos primeras filas para prueba inicial
df_prueba = df.head(2).copy()

# Lista donde guardaremos los resúmenes generados de la prueba
gen_summaries = []

for i, fila in df_prueba.iterrows():
    print(f"\n Procesando {fila['name']} ({i+1}/{len(df_prueba)})...\n")
    resumen, tiempo = call_grok_api(prompt, fila['article'])
    gen_summaries.append(resumen if resumen else "")
    print(f"Tiempo de respuesta: {tiempo:.2f} s\n")

# Añadir columna con los resúmenes generados
df_prueba["gen_summary"] = gen_summaries

# Guardar en CSV la prueba
ruta_salida = "./resultados_grok.csv"
df_prueba.to_csv(ruta_salida, index=False, encoding="utf-8")

print(f"Resultados guardados en: {os.path.abspath(ruta_salida)}")
display(df_prueba)

📄 Procesando 10.1002-14651858.CD009781.pub2 (1/2)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f9244f61-93c9-1110-ff4e-d23bcb06cf72_us-east-1","object":"chat.completion","created":1761481028,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Traumatic co
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
⏱️ Tiempo de respuesta: 22.54 s


📄 Procesando 10.1002-14651858.CD010694.pub2 (2/2)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"444c7a13-19a3-5497-1010-3ba96d6d5136_us-east-1","object":"chat.completion","created":1761481051,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Venous leg u
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
⏱️ Tiempo de respuesta: 20.17 s

✅ Resultados guardados en: c:\Users\braya\OneDrive\Documentos\GitHub\Proyecto-PLN-FLAG\src\api_tests\resultados_grok.csv

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,"Traumatic corneal abrasions, which are scratch..."
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,"Venous leg ulcers are common, long-lasting wou..."

In [ ]:
#Aca vamos a usar todo el dataset
df_groktest = df.copy()

# Lista donde guardaremos los resúmenes generados
gen_summaries = []

# Contador de tiempo total
inicio_total = time.time()

for i, fila in df_groktest.iterrows():
    print(f"\n Procesando {fila['name']} ({i+1}/{len(df_groktest)})...\n")
    resumen, tiempo = call_grok_api(prompt, fila['article'])
    gen_summaries.append(resumen if resumen else "")
    print(f" Tiempo de respuesta: {tiempo:.2f} s\n")

# Añadir columna con los resúmenes generados
df_groktest["gen_summary"] = gen_summaries

# Guardar resultados
ruta_salida = "./results_grok.csv"
df_groktest.to_csv(ruta_salida, index=False, encoding="utf-8")

duracion_total = time.time() - inicio_total
print(f"Resultados guardados en: {os.path.abspath(ruta_salida)}")
print(f"Tiempo total: {duracion_total/60:.2f} minutos ({duracion_total/len(df_groktest):.2f} s por fila en promedio)")

 Procesando 10.1002-14651858.CD009781.pub2 (1/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"a6ea987c-8c14-b180-3908-127181ece4e0_us-east-1","object":"chat.completion","created":1761481071,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Traumatic co
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.40 s


 Procesando 10.1002-14651858.CD010694.pub2 (2/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"30c56dd2-a9d5-2072-c8d5-b1865248e654_us-east-1","object":"chat.completion","created":1761481103,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Venous leg u
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.45 s


 Procesando 10.1002-14651858.CD009416.pub2 (3/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f20d2eb1-2445-8787-dca3-04546ec53211_us-east-1","object":"chat.completion","created":1761481127,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Complex regi
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.47 s


 Procesando 10.1002-14651858.CD004104.pub4 (4/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"5a1615d2-8a21-b2e9-ca4e-ba455db5e67e_us-east-1","object":"chat.completion","created":1761481150,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Non-invasive
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.26 s


 Procesando 10.1002-14651858.CD012689.pub2 (5/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"b405f7f2-0eea-1108-dc57-52656e9fcce9_us-east-1","object":"chat.completion","created":1761481173,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Space sprayi
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 20.94 s


 Procesando 10.1002-14651858.CD010591.pub2 (6/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"662a0084-9744-9918-375f-a5bb33098e0b_us-east-1","object":"chat.completion","created":1761481194,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Non-allergic
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 31.97 s


 Procesando 10.1002-14651858.CD001533.pub6 (7/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f90d62fa-af18-427b-52f6-093edd89d11e_us-east-1","object":"chat.completion","created":1761481226,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Nephrotic sy
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 24.39 s


 Procesando 10.1002-14651858.CD010237.pub2 (8/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"bfa6efcb-546c-2cb5-0624-c95b093c0abc_us-east-1","object":"chat.completion","created":1761481251,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Percutaneous
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 20.50 s


 Procesando 10.1002-14651858.CD013272 (9/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"d02eaccb-a76d-e11a-be72-a4a60be5c772_us-east-1","object":"chat.completion","created":1761481271,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Researchers
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 25.59 s


 Procesando 10.1002-14651858.CD009487.pub3 (10/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"1d89b54e-5507-161b-d6d2-fb1a4c309df6_us-east-1","object":"chat.completion","created":1761481297,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"A parastomal
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 19.11 s


 Procesando 10.1002-14651858.CD004332.pub2 (11/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"7b352223-f62d-f0ef-0391-f91d212b1ca1_us-east-1","object":"chat.completion","created":1761481316,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Alcohol depe
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 13.54 s


 Procesando 10.1002-14651858.CD013757.pub2 (12/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"998bf663-b8b1-0290-6c53-a49d025f74b8_us-east-1","object":"chat.completion","created":1761481330,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Respiratory
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 25.43 s


 Procesando 10.1002-14651858.CD010294.pub2 (13/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c3e00008-8462-9c22-1be4-89914c2f806e_us-east-1","object":"chat.completion","created":1761481355,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Autosomal do
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.21 s


 Procesando 10.1002-14651858.CD009169.pub3 (14/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"30748987-dd5a-3a20-31c0-a890511b1547_us-east-1","object":"chat.completion","created":1761481378,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"This update
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 10.25 s


 Procesando 10.1002-14651858.CD010766.pub2 (15/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"b51ed6bc-f076-fbd8-c9de-b4d36c707906_us-east-1","object":"chat.completion","created":1761481389,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Some researc
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 24.28 s


 Procesando 10.1002-14651858.CD013276.pub2 (16/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f287261f-17a5-8c82-70a9-9839ededdb45_us-east-1","object":"chat.completion","created":1761481413,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Maternity ca
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 21.56 s


 Procesando 10.1002-14651858.CD013206.pub2 (17/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"d234a8ab-535a-31ae-e4f4-3c11cf6e8fea_us-east-1","object":"chat.completion","created":1761481434,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Eczema, also
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.05 s


 Procesando 10.1002-14651858.CD004178.pub2 (18/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"e357f400-6fc7-57c4-b2d0-226937672276_us-east-1","object":"chat.completion","created":1761481466,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"An abdominal
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 24.21 s


 Procesando 10.1002-14651858.CD001808.pub3 (19/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"2da1e3b1-8449-41d8-ad61-2ab747de8f4b_us-east-1","object":"chat.completion","created":1761481490,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"This review
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 24.18 s


 Procesando 10.1002-14651858.CD009445.pub2 (20/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"20feeb47-943a-5bff-c89f-aa8ecf2f2283_us-east-1","object":"chat.completion","created":1761481515,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Informed con
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 20.43 s


 Procesando 10.1002-14651858.CD003833.pub4 (21/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"246589e5-18cf-80cf-073f-0d5fbed279bc_us-east-1","object":"chat.completion","created":1761481535,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Omega-3 fatt
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 20.48 s


 Procesando 10.1002-14651858.CD011219.pub4 (22/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c020b50a-e3c6-e1c8-e0f0-ddf22b1bdac5_us-east-1","object":"chat.completion","created":1761481556,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Newborn babi
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.13 s


 Procesando 10.1002-14651858.CD006887.pub4 (23/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"451b0fb8-d14b-0c06-37c9-8a685dacc733_us-east-1","object":"chat.completion","created":1761481589,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Doctors ofte
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 19.61 s


 Procesando 10.1002-14651858.CD007668.pub3 (24/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"40a77e57-7ad9-cac1-6b88-bed9caebfd4e_us-east-1","object":"chat.completion","created":1761481608,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Antisocial p
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 29.95 s


 Procesando 10.1002-14651858.CD010512.pub2 (25/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"fabfa535-6bf8-7734-80ce-1a367b30f2a7_us-east-1","object":"chat.completion","created":1761481638,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Intermittent
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 19.32 s


 Procesando 10.1002-14651858.CD008872.pub2 (26/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"ecfd8192-5f1b-c40a-628c-4dda95c51506_us-east-1","object":"chat.completion","created":1761481658,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Methotrexate
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.05 s


 Procesando 10.1002-14651858.CD009669.pub4 (27/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"9af4665c-b346-99c2-582b-29019f847a50_us-east-1","object":"chat.completion","created":1761481681,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Cardiogenic
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 31.43 s


 Procesando 10.1002-14651858.CD010698.pub2 (28/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c0bce717-8269-003c-86cb-88de80105d12_us-east-1","object":"chat.completion","created":1761481712,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Procedural s
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 25.18 s


 Procesando 10.1002-14651858.CD012280.pub2 (29/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"062502e8-4f4e-5bc0-94dd-70f8ab1e7699_us-east-1","object":"chat.completion","created":1761481737,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"People going
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 21.21 s


 Procesando 10.1002-14651858.CD010322.pub2 (30/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"fa14110e-280e-5b9d-c7fd-da4016874bf5_us-east-1","object":"chat.completion","created":1761481758,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Caesarean se
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 22.12 s


 Procesando 10.1002-14651858.CD013067.pub2 (31/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"e99fbb27-73a1-ad48-dfc1-2cdc07ead763_us-east-1","object":"chat.completion","created":1761481781,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Chronic coug
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 60.51 s


 Procesando 10.1002-14651858.CD013359.pub2 (32/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"5e82b84c-60c4-0be5-98e0-de510a6678c3_us-east-1","object":"chat.completion","created":1761481841,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Each year, a
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 30.25 s


 Procesando 10.1002-14651858.CD012852.pub2 (33/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"621d9558-f064-3717-21fe-d29f7f16a095_us-east-1","object":"chat.completion","created":1761481871,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Women with a
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 29.53 s


 Procesando 10.1002-14651858.CD003677.pub5 (34/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c9388598-de82-4a49-70c6-15bb402e2525_us-east-1","object":"chat.completion","created":1761481901,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"This review
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 20.73 s


 Procesando 10.1002-14651858.CD011165.pub2 (35/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"3aca43de-8eac-58fb-9bba-b30634b14e9c_us-east-1","object":"chat.completion","created":1761481922,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Obstructive
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 28.32 s


 Procesando 10.1002-14651858.CD004242.pub5 (36/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f510833d-3978-c469-f4e2-766e2a2b0f00_us-east-1","object":"chat.completion","created":1761481950,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Cataracts, w
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 21.62 s


 Procesando 10.1002-14651858.CD011022.pub2 (37/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"055c410d-81ba-0631-1bfe-c24681814751_us-east-1","object":"chat.completion","created":1761481972,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Dementia is
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 27.45 s


 Procesando 10.1002-14651858.CD000227.pub4 (38/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"9b813183-69f1-ccd0-bc16-9fac50647f13_us-east-1","object":"chat.completion","created":1761481999,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"This Cochran
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 27.32 s


 Procesando 10.1002-14651858.CD001902.pub2 (39/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"d61ad2b4-2b7b-0a43-f276-9c99be20a161_us-east-1","object":"chat.completion","created":1761482026,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Epilepsy is
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 23.15 s


 Procesando 10.1002-14651858.CD010502.pub2 (40/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"69994948-fed6-8ed9-3629-7db83c0e684e_us-east-1","object":"chat.completion","created":1761482049,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Group A stre
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 27.53 s


 Procesando 10.1002-14651858.CD013345.pub2 (41/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"964ee1d2-e2d0-c2b3-e5bb-9f70541c17bb_us-east-1","object":"chat.completion","created":1761482077,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Hepatocellul
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 27.13 s


 Procesando 10.1002-14651858.CD005260.pub4 (42/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"11947aa3-52af-21a9-a4d4-9213aef853c9_us-east-1","object":"chat.completion","created":1761482104,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"In the UK, p
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 21.01 s


 Procesando 10.1002-14651858.CD007584.pub2 (43/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"31d25573-07cc-d587-1ec8-d75d2322fbbe_us-east-1","object":"chat.completion","created":1761482125,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"Malignant ge
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 26.55 s


 Procesando 10.1002-14651858.CD008905.pub3 (44/380)...

Código de estado: 200

KeyboardInterrupt:

In [10]:
# Ruta del archivo csv guardado para verificar su contenido.
ruta_csv = "./results_grok.csv"
df_check = pd.read_csv(ruta_csv)


df_check.info()

df_check.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         380 non-null    object
 1   article      380 non-null    object
 2   summary      380 non-null    object
 3   gen_summary  380 non-null    object
dtypes: object(4)
memory usage: 12.0+ KB

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,"Traumatic corneal abrasions, which are scratch..."
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,"Venous leg ulcers are common, long-lasting wou..."
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,"Complex regional pain syndrome, or CRPS, is a ..."
3,10.1002-14651858.CD004104.pub4,Background\r\nNon‐invasive ventilation (NIV) w...,Non‐invasive ventilation for people with respi...,"Non-invasive ventilation, often delivered thro..."
4,10.1002-14651858.CD012689.pub2,Background\r\nSpace spraying is the dispersal ...,Insecticide space spraying for preventing mala...,Space spraying involves releasing a fog of ins...