In [9]:
from dotenv import load_dotenv
import os
import time
import json
import requests
import pandas as pd

# Ruta absoluta o relativa al .env en la raíz del repo
env_path = os.path.abspath(os.path.join(os.getcwd(), "../../..", ".env"))
load_dotenv(dotenv_path=env_path)

# Obtener clave de Grok desde .env
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")

if CLAUDE_API_KEY:
    print("Clave de Claude cargada correctamente.")
else:
    raise ValueError("No se encontró la clave de Claude. Verifica la ruta del .env.")

Clave de Claude cargada correctamente.

In [10]:
def call_claude_api(prompt, text):
    """
    Sends a text and a prompt to Claude Sonnet 3.5 and returns the generated summary.
    """
    url = "https://api.anthropic.com/v1/messages"

    headers = {
        "x-api-key": CLAUDE_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
    }

    payload = {
        "model": "claude-sonnet-4-5",
        "max_tokens": 1024,
        "system": "You are an expert assistant specialized in simplifying biomedical language.",
        "messages": [
            {"role": "user", "content": f"{prompt}\n\nText:\n{text}"}
        ]
    }

    try:
        start_time = time.time()
        response = requests.post(url, headers=headers, json=payload)
        elapsed = time.time() - start_time

        print(f"Status code: {response.status_code}")
        if response.status_code == 200:
            data = response.json()
            print("Response keys:", data.keys())
            output = data["content"][0]["text"]
            return output.strip(), elapsed
        else:
            print(f"HTTP error {response.status_code}: {response.text[:200]}")
            return None, elapsed

    except Exception as e:
        print("Request error:", e)
        return None, None

In [11]:
prompt = "Summarize this biomedical paragraph in plain language for the public."
text = "The administration of statins has been shown to reduce LDL cholesterol and cardiovascular risk."
resumen, tiempo = call_claude_api(prompt, text)
print(resumen)
print(f"Time: {tiempo:.2f} s")

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
# Simplified Summary

Statin medications help lower "bad" cholesterol (LDL) in the blood and reduce the risk of heart disease and stroke.

---

**Key terms explained:**
- **Statins**: Common cholesterol-lowering drugs
- **LDL cholesterol**: "Bad" cholesterol that can clog arteries
- **Cardiovascular risk**: Chance of heart attack or stroke
Time: 4.71 s

In [12]:
ruta_dataset = "../data-sources/pre-processed/data_finetuning_test.csv"
df = pd.read_csv(ruta_dataset, encoding="utf-8", on_bad_lines="skip")
display(df.head(2))

,name,article,summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...

In [ ]:
# Prompt para Claude
prompt = """ou are a helpful medical/health writer.
Summarize the following scientific text into a clear summary intended for a general audience.
Do NOT use headings, titles, bullet points, or numbered lists. Do not invent data or references.
If you must use a technical term, briefly define it."""

# Tomar las dos primeras filas del dataset
df_claude_test = df.head(2).copy()

# Lista donde guardaremos los resúmenes generados
gen_summaries = []

# Procesar las dos filas
for i, fila in df_claude_test.iterrows():
    print(f"\n Processing {fila['name']} ({i+1}/{len(df_claude_test)})...\n")
    resumen, tiempo = call_claude_api(prompt, fila['article'])
    gen_summaries.append(resumen if resumen else "")
    print(f"Response time: {tiempo:.2f} s\n")

# Agregar columna con los resúmenes generados
df_claude_test["gen_summary"] = gen_summaries

# Guardar en CSV
ruta_salida = "./prueba_2filasclaude.csv"
df_claude_test.to_csv(ruta_salida, index=False, encoding="utf-8")

print(f"Results saved to: {os.path.abspath(ruta_salida)}")

# Mostrar los resultados en pantalla
display(df_claude_test)

📄 Processing 10.1002-14651858.CD009781.pub2 (1/2)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.17 s


📄 Processing 10.1002-14651858.CD010694.pub2 (2/2)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.63 s

Results saved to: c:\Users\braya\OneDrive\Documentos\GitHub\Proyecto-PLN-FLAG\src\api_tests\prueba_2filasclaude.csv

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,**Summary**\n\nCorneal abrasions—scratches on ...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,**Summary**\n\nVenous leg ulcers are long-last...

In [14]:
# Código para procesar los 380 registros con Claude
# Prompt para Claude
prompt = """You are a helpful medical/health writer.
Summarize the following scientific text into a clear summary intended for a general audience.
Do NOT use headings, titles, bullet points, or numbered lists. Do not invent data or references.
If you must use a technical term, briefly define it."""

# Copiamos el dataset completo
df_claude_final = df.copy()

# Lista donde guardaremos los resúmenes generados
gen_summaries = []

# Procesar todas las filas
for i, fila in df_claude_final.iterrows():
    print(f"\n Processing {fila['name']} ({i+1}/{len(df_claude_final)})...\n")
    resumen, tiempo = call_claude_api(prompt, fila['article'])
    gen_summaries.append(resumen if resumen else "")
    print(f"⏱️ Response time: {tiempo:.2f} s\n")

# Agregar la columna con los resúmenes generados
df_claude_final["gen_summary"] = gen_summaries

# Guardar en CSV
ruta_salida = "./results_claude.csv"
df_claude_final.to_csv(ruta_salida, index=False, encoding="utf-8")

print(f"Results saved to: {os.path.abspath(ruta_salida)}")

# Mostrar los primeros registros generados
display(df_claude_final.head(3))

 Processing 10.1002-14651858.CD009781.pub2 (1/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.73 s


 Processing 10.1002-14651858.CD010694.pub2 (2/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.17 s


 Processing 10.1002-14651858.CD009416.pub2 (3/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.96 s


 Processing 10.1002-14651858.CD004104.pub4 (4/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.90 s


 Processing 10.1002-14651858.CD012689.pub2 (5/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.55 s


 Processing 10.1002-14651858.CD010591.pub2 (6/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.66 s


 Processing 10.1002-14651858.CD001533.pub6 (7/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.83 s


 Processing 10.1002-14651858.CD010237.pub2 (8/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.29 s


 Processing 10.1002-14651858.CD013272 (9/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.21 s


 Processing 10.1002-14651858.CD009487.pub3 (10/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.74 s


 Processing 10.1002-14651858.CD004332.pub2 (11/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.46 s


 Processing 10.1002-14651858.CD013757.pub2 (12/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.72 s


 Processing 10.1002-14651858.CD010294.pub2 (13/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.66 s


 Processing 10.1002-14651858.CD009169.pub3 (14/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.99 s


 Processing 10.1002-14651858.CD010766.pub2 (15/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.84 s


 Processing 10.1002-14651858.CD013276.pub2 (16/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 15.12 s


 Processing 10.1002-14651858.CD013206.pub2 (17/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.54 s


 Processing 10.1002-14651858.CD004178.pub2 (18/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 18.02 s


 Processing 10.1002-14651858.CD001808.pub3 (19/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.29 s


 Processing 10.1002-14651858.CD009445.pub2 (20/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.09 s


 Processing 10.1002-14651858.CD003833.pub4 (21/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.78 s


 Processing 10.1002-14651858.CD011219.pub4 (22/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.65 s


 Processing 10.1002-14651858.CD006887.pub4 (23/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.13 s


 Processing 10.1002-14651858.CD007668.pub3 (24/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 16.01 s


 Processing 10.1002-14651858.CD010512.pub2 (25/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.73 s


 Processing 10.1002-14651858.CD008872.pub2 (26/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.83 s


 Processing 10.1002-14651858.CD009669.pub4 (27/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.04 s


 Processing 10.1002-14651858.CD010698.pub2 (28/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.25 s


 Processing 10.1002-14651858.CD012280.pub2 (29/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.54 s


 Processing 10.1002-14651858.CD010322.pub2 (30/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.62 s


 Processing 10.1002-14651858.CD013067.pub2 (31/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.27 s


 Processing 10.1002-14651858.CD013359.pub2 (32/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.13 s


 Processing 10.1002-14651858.CD012852.pub2 (33/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.31 s


 Processing 10.1002-14651858.CD003677.pub5 (34/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.86 s


 Processing 10.1002-14651858.CD011165.pub2 (35/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 15.81 s


 Processing 10.1002-14651858.CD004242.pub5 (36/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.41 s


 Processing 10.1002-14651858.CD011022.pub2 (37/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.85 s


 Processing 10.1002-14651858.CD000227.pub4 (38/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.56 s


 Processing 10.1002-14651858.CD001902.pub2 (39/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 15.34 s


 Processing 10.1002-14651858.CD010502.pub2 (40/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.83 s


 Processing 10.1002-14651858.CD013345.pub2 (41/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.72 s


 Processing 10.1002-14651858.CD005260.pub4 (42/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.28 s


 Processing 10.1002-14651858.CD007584.pub2 (43/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.37 s


 Processing 10.1002-14651858.CD008905.pub3 (44/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.44 s


 Processing 10.1002-14651858.CD010176.pub3 (45/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 15.69 s


 Processing 10.1002-14651858.CD011895.pub2 (46/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.78 s


 Processing 10.1002-14651858.CD007086.pub2 (47/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.31 s


 Processing 10.1002-14651858.CD009417.pub2 (48/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.85 s


 Processing 10.1002-14651858.CD012136.pub2 (49/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.81 s


 Processing 10.1002-14651858.CD013357.pub2 (50/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.74 s


 Processing 10.1002-14651858.CD006902.pub3 (51/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 15.94 s


 Processing 10.1002-14651858.CD007361.pub2 (52/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 8.63 s


 Processing 10.1002-14651858.CD001331 (53/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.87 s


 Processing 10.1002-14651858.CD010134.pub2 (54/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.73 s


 Processing 10.1002-14651858.CD003928.pub3 (55/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.16 s


 Processing 10.1002-14651858.CD011014.pub2 (56/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.32 s


 Processing 10.1002-14651858.CD005200.pub3 (57/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.42 s


 Processing 10.1002-14651858.CD007271.pub3 (58/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.42 s


 Processing 10.1002-14651858.CD006978.pub2 (59/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.08 s


 Processing 10.1002-14651858.CD011837.pub2 (60/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.70 s


 Processing 10.1002-14651858.CD012548.pub2 (61/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.97 s


 Processing 10.1002-14651858.CD009281.pub3 (62/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 8.92 s


 Processing 10.1002-14651858.CD009624.pub2 (63/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.79 s


 Processing 10.1002-14651858.CD009587.pub2 (64/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.03 s


 Processing 10.1002-14651858.CD012941.pub2 (65/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.11 s


 Processing 10.1002-14651858.CD007524.pub4 (66/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.85 s


 Processing 10.1002-14651858.CD005004.pub3 (67/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.15 s


 Processing 10.1002-14651858.CD013504.pub2 (68/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.51 s


 Processing 10.1002-14651858.CD003879.pub5 (69/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 21.32 s


 Processing 10.1002-14651858.CD012705.pub2 (70/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.34 s


 Processing 10.1002-14651858.CD009573.pub2 (71/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.92 s


 Processing 10.1002-14651858.CD003811.pub3 (72/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.90 s


 Processing 10.1002-14651858.CD011285.pub2 (73/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.71 s


 Processing 10.1002-14651858.CD006650.pub5 (74/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.24 s


 Processing 10.1002-14651858.CD012024.pub3 (75/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.46 s


 Processing 10.1002-14651858.CD012760.pub2 (76/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 13.42 s


 Processing 10.1002-14651858.CD003044.pub4 (77/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.61 s


 Processing 10.1002-14651858.CD001977.pub2 (78/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.98 s


 Processing 10.1002-14651858.CD014798.pub2 (79/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.93 s


 Processing 10.1002-14651858.CD007775.pub2 (80/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.88 s


 Processing 10.1002-14651858.CD009369.pub2 (81/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 14.77 s


 Processing 10.1002-14651858.CD002788.pub3 (82/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.80 s


 Processing 10.1002-14651858.CD005107.pub4 (83/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.33 s


 Processing 10.1002-14651858.CD008327.pub2 (84/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.53 s


 Processing 10.1002-14651858.CD011991.pub2 (85/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 9.33 s


 Processing 10.1002-14651858.CD005589.pub2 (86/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.18 s


 Processing 10.1002-14651858.CD003170.pub4 (87/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 11.60 s


 Processing 10.1002-14651858.CD004956.pub3 (88/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 16.71 s


 Processing 10.1002-14651858.CD004203.pub3 (89/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.49 s


 Processing 10.1002-14651858.CD007346.pub3 (90/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.10 s


 Processing 10.1002-14651858.CD000071.pub4 (91/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 12.98 s


 Processing 10.1002-14651858.CD009366.pub2 (92/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 18.54 s


 Processing 10.1002-14651858.CD000475.pub4 (93/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.51 s


 Processing 10.1002-14651858.CD006512.pub2 (94/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
⏱️ Response time: 10.27 s


 Processing 10.1002-14651858.CD006899.pub3 (95/380)...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,**Summary for General Audience:**\n\nCorneal a...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,**Summary for General Audience**\n\nVenous leg...
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,## Plain Language Summary\n\n**Background**\nC...

In [17]:
# Ruta del archivo csv guardado para verificar su contenido.
ruta_csv = "./results_claude.csv"
df_check = pd.read_csv(ruta_csv)


df_check.info()

df_check.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         380 non-null    object
 1   article      380 non-null    object
 2   summary      380 non-null    object
 3   gen_summary  379 non-null    object
dtypes: object(4)
memory usage: 12.0+ KB

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,**Summary for General Audience:**\n\nCorneal a...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,**Summary for General Audience**\n\nVenous leg...
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,## Plain Language Summary\n\n**Background**\nC...
3,10.1002-14651858.CD004104.pub4,Background\r\nNon‐invasive ventilation (NIV) w...,Non‐invasive ventilation for people with respi...,Summary for General Audience:\n\nWhen people w...
4,10.1002-14651858.CD012689.pub2,Background\r\nSpace spraying is the dispersal ...,Insecticide space spraying for preventing mala...,## Plain Language Summary\n\n**Background**\n\...

In [18]:
# Filtrar la fila faltante
faltante = df_check[df_check["gen_summary"].isnull()]
print(f"🔍 Faltan {len(faltante)} resúmenes.")
display(faltante[["name", "article"]])

🔍 Faltan 1 resúmenes.

,name,article
203,10.1002-14651858.CD004796.pub2,Background\r\nInfantile colic is a common diso...

In [19]:
# Reprocesar solo esa fila
if not faltante.empty:
    for i, fila in faltante.iterrows():
        print(f"\n♻️ Reprocesando {fila['name']}...\n")
        resumen, tiempo = call_claude_api(prompt, fila['article'])
        df_check.loc[i, "gen_summary"] = resumen if resumen else ""
        print(f"✅ Reparado en {tiempo:.2f} s")

# Guardar nuevamente el CSV actualizado
df_check.to_csv(ruta_csv, index=False, encoding="utf-8")
print(f"✅ Archivo actualizado: {os.path.abspath(ruta_csv)}")

♻️ Reprocesando 10.1002-14651858.CD004796.pub2...

Status code: 200
Response keys: dict_keys(['model', 'id', 'type', 'role', 'content', 'stop_reason', 'stop_sequence', 'usage'])
✅ Reparado en 12.79 s
✅ Archivo actualizado: c:\Users\braya\OneDrive\Documentos\GitHub\Proyecto-PLN-FLAG\src\api_tests\results_claude.csv

In [20]:
# Ruta del archivo csv guardado para verificar su contenido.
ruta_csv = "./results_claude.csv"
df_check = pd.read_csv(ruta_csv)


df_check.info()

df_check.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         380 non-null    object
 1   article      380 non-null    object
 2   summary      380 non-null    object
 3   gen_summary  380 non-null    object
dtypes: object(4)
memory usage: 12.0+ KB

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,**Summary for General Audience:**\n\nCorneal a...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,**Summary for General Audience**\n\nVenous leg...
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,## Plain Language Summary\n\n**Background**\nC...
3,10.1002-14651858.CD004104.pub4,Background\r\nNon‐invasive ventilation (NIV) w...,Non‐invasive ventilation for people with respi...,Summary for General Audience:\n\nWhen people w...
4,10.1002-14651858.CD012689.pub2,Background\r\nSpace spraying is the dispersal ...,Insecticide space spraying for preventing mala...,## Plain Language Summary\n\n**Background**\n\...